apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
  labels:
    app: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
        - name: video-transcoder
          image: kjelstromjr/video-transcoder
          ports:
            - containerPort: 8080
        - name: hls-streaming-server
          image: kjelstromjr/hls-streaming-server
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  selector:
    app: streaming
  ports:
    - name: transcoder
      port: 8080
      targetPort: 8080
    - name: streaming
      port: 8081
      targetPort: 8081
  type: ClusterIP
